# Generated by Django 5.1 on 2024-08-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
