# Generated by Django 4.2.4 on 2024-09-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgss', '0011_org_package_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('package9', 'Package 9')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_details', models.TextField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgss.org')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.package')),
            ],
        ),
    ]
