# Generated by Django 4.2.4 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
