# Generated by Django 4.2.4 on 2024-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_package_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('package9', 'Package 9')], max_length=50, null=True),
        ),
    ]
