# Generated by Django 5.1 on 2024-08-24 05:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('pre', 'PRE CHOICE'), ('mid', 'MID CHOICE'), ('post', 'POST CHOICE')], default=None, max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('difficult', 'Difficult')], default='easy', max_length=30)),
                ('timer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'PRE CHOICE'), ('mid', 'MID CHOICE'), ('post', 'POST CHOICE')], default=None, max_length=30)),
                ('result', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passing_criteria', models.IntegerField(default=60)),
                ('positive_marks', models.IntegerField(blank=True, null=True)),
                ('negative_marks', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('trigger_point', models.CharField(choices=[('days', 'DAYS'), ('perentage', 'PERCENTAGE')], default=None, max_length=30)),
                ('refresher_days', models.IntegerField(blank=True, null=True)),
                ('suborg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgss.suborg')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttype'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(to='assessments.question'),
        ),
    ]
