# Generated by Django 4.2.4 on 2024-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessmenttype_suborg'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.FileField(blank=True, null=True, upload_to='media/option/option_image'),
        ),
    ]
