# Generated by Django 4.2.4 on 2024-10-08 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0015_org_expires_on'),
        ('assessments', '0003_option_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='suborg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.suborg1'),
        ),
    ]
