# Generated by Django 4.2.4 on 2024-10-08 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0015_org_expires_on'),
        ('assessments', '0004_question_suborg'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='org',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='orgss.org'),
        ),
    ]
