# Generated by Django 4.2.4 on 2024-10-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='phase',
        ),
    ]
