# Generated by Django 4.2.4 on 2024-10-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_assessmentresult_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='created_at',
        ),
    ]
