# Generated by Django 4.2.4 on 2024-10-08 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_assessmentresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
