# Generated by Django 4.2.4 on 2024-10-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_option_option_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_image',
            field=models.FileField(blank=True, null=True, upload_to='media/option/option_image'),
        ),
    ]
