# Generated by Django 4.2.4 on 2024-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_option_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
