# Generated by Django 4.2.4 on 2024-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_assessmenttype_is_approved_assessmenttype_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='assessments.question'),
        ),
    ]
