# Generated by Django 4.2.4 on 2024-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_assessment_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, to='assessments.question'),
        ),
    ]
