# Generated by Django 4.2.4 on 2024-10-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_assessment_suborg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttype',
            name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='passing_criteria',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='positive_marks',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='refresher_days',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='time',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='trigger_point',
        ),
    ]
