# Generated by Django 4.2.4 on 2024-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='validity',
            field=models.IntegerField(default=30),
        ),
    ]
