# Generated by Django 4.2.4 on 2024-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_org_is_active_org_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('sub-admin', 'Sub-Admin'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
