# Generated by Django 4.2.4 on 2024-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0003_remove_role_name_role_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('employee', 'Employee'), ('sub-admin', 'Sub-Admin'), ('admin', 'Admin')], default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='suborg',
        ),
        migrations.RemoveField(
            model_name='suborg',
            name='org',
        ),
    ]
