# Generated by Django 4.2.4 on 2024-09-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessmenttype_suborg'),
        ('users', '0002_alter_usersuborgs_suborg'),
        ('zola', '0004_alter_item_role'),
        ('series', '0005_alter_series_sub_org'),
        ('learningcourse', '0002_alter_learningcourse_sub_org'),
        ('orgss', '0004_role1_suborg1_remove_role_suborg_remove_suborg_org'),
        ('accounts', '0014_alter_account_role_alter_account_sub_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='suborg1',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='orgss.org'),
        ),
        migrations.AddField(
            model_name='role1',
            name='suborg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborgrole', to='orgss.suborg1'),
        ),
        migrations.AlterField(
            model_name='weightage',
            name='suborg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborg', to='orgss.suborg1'),
        ),
        migrations.DeleteModel(
            name='SubOrg',
        ),
    ]
