# Generated by Django 4.2.4 on 2024-09-09 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0007_rename_name1_suborg1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='suborg1',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
