# Generated by Django 4.2.4 on 2024-09-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0008_org_created_at_suborg1_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='number_of_logins',
            field=models.IntegerField(default=9),
        ),
    ]
