# Generated by Django 4.2.4 on 2024-09-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0009_org_number_of_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
