# Generated by Django 4.2.4 on 2024-09-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0010_alter_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='package_purchased',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
