# Generated by Django 4.2.4 on 2024-09-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0011_org_package_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborg1',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
