# Generated by Django 4.2.4 on 2024-09-23 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0012_alter_suborg1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='upgrade_expiry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
