# Generated by Django 4.2.4 on 2024-09-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0013_org_upgrade_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='upgrade_expiry',
        ),
    ]
