# Generated by Django 4.2.4 on 2024-09-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
