# Generated by Django 5.1 on 2024-08-28 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, default='tags', max_length=256),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zola.item'),
        ),
    ]
