# Generated by Django 4.2.4 on 2024-09-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0004_role1_suborg1_remove_role_suborg_remove_suborg_org'),
        ('zola', '0003_item_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seanrole', to='orgss.role1'),
        ),
    ]
