# Generated by Django 4.2.4 on 2024-09-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0004_alter_item_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.TextField(blank=True, default='tags', null=True),
        ),
    ]
