# Generated by Django 4.2.4 on 2024-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0006_item_library_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='library_filter',
            field=models.CharField(choices=[('team player', 'Team Player'), ('sales', 'Sales'), ('will stick or not', 'Will Stick or Not'), ('intrapreneurial', 'Intrapreneurial'), ('handling pressure', 'Handling Pressure'), ('managing conflicts', 'Managing Conflicts'), ('handling customers', 'Handling Customers'), ('interpersonal skills', 'Interpersonal Skills'), ('managing people', 'Managing People')], default='sales', max_length=30),
        ),
    ]
