# Generated by Django 4.2.4 on 2024-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0007_alter_item_library_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='library_filter',
            field=models.CharField(choices=[('team player', 'Team Player'), ('sales', 'Sales'), ('handling customers', 'Handling Customers')], default='sales', max_length=30),
        ),
    ]
