# Generated by Django 4.2.4 on 2024-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0011_alter_item_library_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
