# Generated by Django 4.2.4 on 2024-10-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zola', '0012_libraryfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='library_filter',
        ),
        migrations.AddField(
            model_name='item',
            name='library_filter',
            field=models.ManyToManyField(default='Sales', to='zola.libraryfilter'),
        ),
    ]
