# Generated by Django 5.1 on 2024-08-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zola', '0002_item_tags_suggestion_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(blank=True, max_length=256, null=True)),
                ('item', models.ForeignKey(default='sentences', on_delete=django.db.models.deletion.CASCADE, to='zola.item')),
            ],
        ),
    ]
