# Generated by Django 5.1 on 2024-08-23 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PowerWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('sentence', models.CharField(default='sentence', max_length=250)),
                ('power_word_name', models.CharField(default='pw', max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pww', to='words.words')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=-7)),
                ('sentence', models.CharField(default='sentence', max_length=250)),
                ('negative_word_name', models.CharField(default='ww', max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nww', to='words.words')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_word_name', models.CharField(max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eww', to='words.words')),
            ],
        ),
    ]
