# Generated by Django 5.1 on 2024-09-02 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_number',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='account',
            name='validity',
            field=models.IntegerField(default=30),
        ),
    ]
