# Generated by Django 4.2.4 on 2024-09-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_org_is_active_org_validity'),
        ('accounts', '0002_account_contact_number_account_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org'),
        ),
    ]
