# Generated by Django 4.2.4 on 2024-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jadu_asked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jadu_attempted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pw_competency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quiz_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quizzes_attempted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quizzes_streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scenario_attempt_pw',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scenario_attempt_ww',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_scenario_saved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ww_competency',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
