# Generated by Django 4.2.4 on 2024-09-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scenarios_attempted',
            field=models.IntegerField(default=1),
        ),
    ]
