# Generated by Django 4.2.4 on 2024-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_scenarios_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='noscenarios_attempted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
