# Generated by Django 4.2.4 on 2024-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_noscenarios_attempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='noscenarios_attempted',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scenarios_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
