# Generated by Django 4.2.4 on 2024-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_scenarios_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scenarios_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
