# Generated by Django 4.2.4 on 2024-09-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0003_remove_role_name_role_role_type'),
        ('accounts', '0010_alter_userprofile_scenarios_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.suborg'),
        ),
    ]
