# Generated by Django 4.2.4 on 2024-09-09 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_account_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 9, 54, 35, 187776, tzinfo=datetime.timezone.utc)),
        ),
    ]
