# Generated by Django 4.2.4 on 2024-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_account_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='validity',
            field=models.IntegerField(default=30),
        ),
    ]
