# Generated by Django 4.2.4 on 2024-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_account_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(editable=False, max_length=70, unique=True),
        ),
    ]
