# Generated by Django 4.2.4 on 2024-09-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_account_active_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
