# Generated by Django 4.2.4 on 2024-09-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0011_org_package_purchased'),
        ('accounts', '0025_alter_account_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org'),
        ),
    ]
