# Generated by Django 4.2.4 on 2024-10-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assessment_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
