# Generated by Django 4.2.4 on 2024-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_assessment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_level_score',
            field=models.IntegerField(default=0),
        ),
    ]
