# Generated by Django 5.1 on 2024-08-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('master_competency', models.ManyToManyField(blank=True, to='competency.competency')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='competency_sentiment',
            field=models.ManyToManyField(blank=True, to='competency.senti'),
        ),
        migrations.CreateModel(
            name='Sub_Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('emotion_words', models.ManyToManyField(blank=True, to='words.emotionwords')),
                ('negative_words', models.ManyToManyField(blank=True, to='words.negativewords')),
                ('power_words', models.ManyToManyField(blank=True, to='words.powerwords')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='sub_competency',
            field=models.ManyToManyField(blank=True, to='competency.sub_competency'),
        ),
    ]
