# Generated by Django 5.1 on 2024-08-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('orgss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media/series/seasons/thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonLota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/seasons/lota')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.seasons')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media/series/thumbnail')),
                ('sub_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgss.suborg')),
            ],
        ),
        migrations.AddField(
            model_name='seasons',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series'),
        ),
    ]
