# Generated by Django 5.1 on 2024-08-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcourse', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcourse.learningcourse')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.seasons')),
            ],
        ),
    ]
