# Generated by Django 5.1 on 2024-08-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_itemseason'),
        ('zola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemseason',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zola.item'),
        ),
        migrations.AddField(
            model_name='itemseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.seasons'),
        ),
    ]
