# Generated by Django 4.2.4 on 2024-09-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_alter_series_sub_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
