# Generated by Django 4.2.4 on 2024-09-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50),
        ),
    ]
