# Generated by Django 4.2.4 on 2024-09-23 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0002_alter_upgrade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradedetail',
            name='additional_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upgradedetail',
            name='expires_on',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('package 9', 'Package 9')], max_length=50),
        ),
    ]
