# Generated by Django 4.2.4 on 2024-09-27 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0003_upgradedetail_additional_logins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradedetail',
            name='expires_on',
            field=models.DateField(default=datetime.date(2024, 10, 27)),
        ),
    ]
