# Generated by Django 4.2.4 on 2024-09-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0004_alter_upgradedetail_expires_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradedetail',
            name='additional_logins',
        ),
        migrations.RemoveField(
            model_name='upgradedetail',
            name='expires_on',
        ),
    ]
