# Generated by Django 4.2.4 on 2024-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0007_alter_upgradedetail_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradedetail',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
