# Generated by Django 4.2.4 on 2024-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0008_alter_upgradedetail_expires_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('no_assessment', 'No MCQ Assessment'), ('assessment30', '30 MCQ Questions'), ('assessment60', '60 MCQ Questions')], max_length=90)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50),
        ),
    ]
