# Generated by Django 4.2.4 on 2024-10-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0009_upgradeassessment_alter_upgrade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='assessment_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upgradeassessment', to='upgrade.upgradeassessment'),
        ),
    ]
