# Generated by Django 4.2.4 on 2024-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0011_remove_upgrade_assessment_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradedetail',
            name='assessment_package',
            field=models.ManyToManyField(blank=True, default=1, to='upgrade.upgradeassessment'),
        ),
    ]
