# Generated by Django 4.2.4 on 2024-10-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0012_upgradedetail_assessment_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradedetail',
            name='assessment_package',
        ),
        migrations.AddField(
            model_name='upgradedetail',
            name='assessment_package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
