# Generated by Django 4.2.4 on 2024-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='media/item/thumbnail'),
        ),
    ]
