# Generated by Django 4.2.4 on 2024-09-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_textresouce'),
    ]

    operations = [
        migrations.AddField(
            model_name='textresouce',
            name='video',
            field=models.URLField(blank=True, default='https://www.youtube.com/watch?v=tfrvVKM0DZY', null=True),
        ),
    ]
